export enum BusType {
  NORMAL = 'NORMAL',
  SEMI_LUXURY = 'SEMI_LUXURY',
  LUXURY = 'LUXURY',
  SUPER_LUXURY = 'SUPER_LUXURY',
  EXPRESSWAY = 'EXPRESSWAY',
  SISU_SERIYA = 'SISU_SERIYA',
  NISI_SERIYA = 'NISI_SERIYA',
  OFFICE_TRANSPORT = 'OFFICE_TRANSPORT',
  TOURIST_CHARTER = 'TOURIST_CHARTER',
}
