export enum FileDocumentType {
  PROFILE_PICTURE = 'PROFILE_PICTURE',
  CONDUCTOR_LICENSE = 'CONDUCTOR_LICENSE',
  NIC_DOCUMENT = 'NIC_DOCUMENT',
  RC = 'RC',
  INSURANCE = 'INSURANCE',
  FITNESS = 'FITNESS',
  OTHER = 'OTHER',
}
